# **Problem 3.28**

At point $P$ in acontinuum body, the stress tensor components are given in MPa with respect to the axes $Px_1x_2x_3$ by the matrix

$$ [t_{ij}] =
\begin{bmatrix}
    1 & -3 & \sqrt2 \\
    -3 & 1 & -\sqrt2 \\
    \sqrt2 & -\sqrt2 & 4
\end{bmatrix}
$$

Determine  
(a) the principal stress values $\sigma_{I}$,$\sigma_{II}$ and $\sigma_{III}$ together with the corresponding principal directions  
(b) The stress invariants $I_T$, $II_T$ and $III_T$  
(c) The maximum shear stress value and the normal to the plane on wich it acts  
(d) the principal deviator stress values    
(e) the stress vector on the octahedral plane together with it's normal and shear components  
(f) the stress matrix for axes rotated 60° counterclockwise with respect to the axis $PQ$, which makes equal angles relative to the coordinate axes $Px_1x_2x_3$

# Solving

(a) Principal stress values and principal stress directiones

In [ ]:
import numpy as np
t = np.array([[1,-3,np.sqrt(2)],
              [-3,1,-np.sqrt(2)],
              [np.sqrt(2),-np.sqrt(2),4]])

In [ ]:
values, directions = np.linalg.eig(t)

print("Principal stress values")
print(values)
print("\n")
print("Principal stress directions")
print(directions)


Principal stress values
[ 6. -2.  2.]


Principal stress directions
[[-5.00000000e-01  7.07106781e-01 -5.00000000e-01]
 [ 5.00000000e-01  7.07106781e-01  5.00000000e-01]
 [-7.07106781e-01  1.92232847e-16  7.07106781e-01]]


(b) the stress invariants

In [ ]:
IT = np.trace(t)
IT

6.0

In [ ]:
IIT = (1/2)*((np.trace(t))**2 - np.trace(t**2))
IIT

9.0

In [ ]:
IIIT = np.linalg.det(t)
IIIT

-24.000000000000014

(c) The maximum shear stress value and the normal to the plane on wich it acts

$$ \sigma_{max} = \max \left( \left| \frac{\sigma_1}{2} \right|, \left| \frac{\sigma_2}{2} \right|, \left| \frac{\sigma_3}{2} \right|, \left| \frac{\sigma_1 - \sigma_2}{2} \right|, \left| \frac{\sigma_1 - \sigma_3}{2} \right|, \left| \frac{\sigma31 - \sigma_2}{2} \right| \right) $$

In [ ]:
sigma1,sigma2,sigma3 = np.linalg.eig(t)[0][0],np.linalg.eig(t)[0][1],np.linalg.eig(t)[0][2]

sigmas = [abs(sigma1/2), abs(sigma2/2), abs(sigma3/2), abs(sigma1 - sigma2)/2, abs(sigma1 -sigma3)/2, abs(sigma2-sigma3)/2]

In [ ]:
max(sigmas)

3.999999999999999

(d) The principal deviator stress values

We know that 

$$\sigma_M = \frac{t_{ij}}{3} = \frac{T_{kk}}{2} = \frac{4}{2}$$

We define deviatoric stress to be 

$$S = T - \frac{T_{kk}}{2} I$$

Then 

$$ [t_{ij}] =

\begin{bmatrix}
    1 & -3 & \sqrt2 \\
    -3 & 1 & -\sqrt2 \\
    \sqrt2 & -\sqrt2 & 4
\end{bmatrix}

-
\begin{bmatrix}
    4/2 & 0 & 0 \\
    0 & 4/2 & 0 \\
    0 & 0 & 4/2
\end{bmatrix}
$$

In [ ]:
T_kk = np.array([[4/2,0,0],
                 [0,4/2,0],
                 [0,0,4/2]])
T_kk

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [ ]:
s = t - T_kk
print(s)

[[-1.         -3.          1.41421356]
 [-3.         -1.         -1.41421356]
 [ 1.41421356 -1.41421356  2.        ]]


In [ ]:
np.linalg.eig(s)[0]

array([ 4.00000000e+00, -4.00000000e+00, -1.25961676e-16])