# **Problem 3.29**

In a continuum, the stress field relative to the axes $Ox_1x_2x_3$ is given by 

$$ [t_{ij}] =
\begin{bmatrix}
    x_1^2x_2 & x_1(1 - x_2^2) & 0 \\
    x_1(1 - x_2^2) & \frac{1}{3}(x_2^2 - 3x_2) & 0 \\
    0 & 0 & 2x_3^2
\end{bmatrix}
$$

Determine  
(a) the body force distribution if the equilibrium equations are to be satisfied throughtout the field  
(b) the principal stresses at $P(a,0,2\sqrt a)$  
(c) the maximum shear stress at $P$  
(d) the principal deviator stresses at $P$ 

## Solving

(a) Equilibrium equations are given by:

$$t_{ij}+ \rho b_{i} = 0$$

$$\frac{\partial t_{x1x1}}{\partial x_1} + \frac{\partial t_{x1x2}}{\partial x_2} + \frac{\partial t_{x1x3}}{\partial x_3} + \rho b_{1} = 0$$

$$\frac{\partial t_{x2x1}}{\partial x_1} + \frac{\partial t_{x2x2}}{\partial x_2} + \frac{\partial t_{x2x3}}{\partial x_3} + \rho b_{2} = 0$$

$$\frac{\partial t_{x3x1}}{\partial x_1} + \frac{\partial t_{x3x2}}{\partial x_2} + \frac{\partial t_{x3x3}}{\partial x_3} + \rho b_{3} = 0$$


In [ ]:
from sympy import *

init_printing()

x1,x2,x3,rho, b1,b2,b3 = symbols('x_1 x_2 x_3 rho b_1 b_2 b_3')

t_x1x1 = x1**2 * x2
t_x1x2 = x1*(1-x2**2)
t_x1x3 = 0
t_x2x1 = x1*(1-x2**2)
t_x2x2 = (1/3)*(x2**2 - 3*x2)
t_x2x3 = 0
t_x3x1 = 0
t_x3x2 = 0
t_x3x3 = 2*x3**2


Now, we calculate the equilibrium equations with the necessary derivatives, solving for every $b_i$:

$b_1$

In [ ]:
solve(diff(t_x1x1,x1) + diff(t_x1x2,x2) + diff(t_x1x3,x3) + rho*b1,b1)

[0]

$b_2$

In [ ]:
solve(diff(t_x2x1,x1) + diff(t_x2x2,x2) + diff(t_x2x3,x3) + rho*b2,b2)

⎡0.333333333333333⋅x₂⋅(3.0⋅x₂ - 2.0)⎤
⎢───────────────────────────────────⎥
⎣                 ρ                 ⎦

$b_3$

In [ ]:
solve(diff(t_x3x1,x1) + diff(t_x3x2,x2) + diff(t_x3x3,x3) + rho*b3,b3)

⎡-4⋅x₃ ⎤
⎢──────⎥
⎣  ρ   ⎦

Now, lets build our matrix $t_{ij}$ evaluated at $P(a,0,2\sqrt a)$


$$ [t_{ij}] \Bigr|_P =
\begin{bmatrix}
    a^2 \cdot 0 & a(1 - 0^2) & 0 \\
    a(1 - 0^2) & \frac{1}{3}(0^2 - 3\cdot 0) & 0 \\
    0 & 0 & 2(2\sqrt a)^2
\end{bmatrix}
$$

Then we have 

$$ [t_{ij}]\Bigr|_P =
\begin{bmatrix}
    0 & a & 0 \\
    a & 0 & 0 \\
    0 & 0 & 8a
\end{bmatrix}
$$


In [ ]:
import numpy as np
a = symbols('a')
t_P = np.array([[0,1,0],[1,0,0],[0,0,8]])
np.linalg.eig(t_P)[0] * a

array([1.0*a, -1.0*a, 8.0*a], dtype=object)

Now for the maximum shear strees at $P(a,0,2\sqrt a)$, we know that

$$ \sigma_s = \frac{1}{2} \left| \sigma_{max} - \sigma_{min} \right| $$

In [ ]:
(1/2) * abs(8*a - (-1*a))

4.5⋅│a│

Finally, let's find the principal deviator stresses at $P$

We know that

$$\sigma_M = \frac{t_{ij}}{3} = \frac{8a}{3} = \frac{T_{kk}}{3}$$

We define deviatoric stress to be

$$ S = T\Bigr|_P - \frac{T_{kk}}{3} I, \quad
[S] =
\begin{bmatrix}
    -\frac{8}{3}a -s & a & 0 \\
    a & -\frac{8}{3}a -s & 0 \\
    0 & 0 & \frac{16a}{3} -s
\end{bmatrix}
$$

Now, in order to obtain the principal stresses, we do $s=0$

$$ [S] =
\begin{bmatrix}
    -\frac{8}{3}a  & a & 0 \\
    a & -\frac{8}{3}a  & 0 \\
    0 & 0 & \frac{16a}{3} 
\end{bmatrix}
$$


In [ ]:
S = np.array([[-8/3, 1,0],
              [1,-8/3,0],
              [0,0,16/3]])
print(S)

[[-2.66666667  1.          0.        ]
 [ 1.         -2.66666667  0.        ]
 [ 0.          0.          5.33333333]]


In [ ]:
np.linalg.eig(S)[0] * a

array([-1.66666666666667*a, -3.66666666666667*a, 5.33333333333333*a],
      dtype=object)